services:
  app:
    image: node:24.2-slim
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ./src:/app
      - node_modules-vol:/app/node_modules
    ports:
      - "5173:5173"
    command: >
      bash -c "npm i &&
      npm run dev -- --host"

volumes:
  node_modules-vol:
