services:
  app:
    image: node:24.2-slim
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ./src/chatapp:/app
      - node_modules-vol:/app/node_modules
    ports:
      - 3000:3000
    command: >
      bash -c "npm i && npm start"

volumes:
  node_modules-vol:
